#!/bin/sh

[ $(which astyle) ] || exit 1

function astyle_commit ()
{
    echo -n "astyle'ing commited files..."
    # only astyle what has changed 
    for i in $(git diff-index --name-only HEAD)
    do
	# only astyle what is a sourcefile
	if echo $i | grep "\(.cpp\|.h\)" ; then 
	    astyle --options=$(pwd)/astylerc $i
            #re-add it to the index so that changes are combined into one commit
	    git add $i 
	fi
    done
    echo "done"
}

if test -d $(pwd)/.git ; then  # daddy are we there yet?
    astyle_commit 
else  # soon love
    cd $(git rev-parse --git-dir | sed s/\.git//)
    astyle_commit 
fi
find -name '*.orig' -delete
