#ifndef GLUON_GRAPHICS_EXPORT_H
#define GLUON_GRAPHICS_EXPORT_H

#include <QtCore/qglobal.h>

#ifndef GLUON_GRAPHICS_EXPORT
    #if defined(MAKE_GLUON_GRAPHICS_LIB)
        #define GLUON_GRAPHICS_EXPORT Q_DECL_EXPORT
    #else
        #define GLUON_GRAPHICS_EXPORT Q_DECL_IMPORT
    #endif
#endif

#ifndef GLUON_GRAPHICS_EXPORT_DEPRECATED
    #define GLUON_GRAPHICS_EXPORT_DEPRECATED Q_DECL_DEPRECATED GLUON_GRAPHICS_EXPORT
#endif

#endif // GLUON_GRAPHICS_EXPORT_H
