#ifndef GLUON_INPUT_EXPORT_H
#define GLUON_INPUT_EXPORT_H

#include <QtCore/qglobal.h>

#ifndef GLUON_INPUT_EXPORT
#if defined(MAKE_GLUON_INPUT_LIB)
#define GLUON_INPUT_EXPORT Q_DECL_EXPORT
#else
#define GLUON_INPUT_EXPORT Q_DECL_IMPORT
#endif
#endif

#ifndef GLUON_INPUT_EXPORT_DEPRECATED
#define GLUON_INPUT_EXPORT_DEPRECATED Q_DECL_DEPRECATED GLUON_INPUT_EXPORT
#endif

#endif // GLUON_INPUT_EXPORT_H
